import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card } from '@/components/ui/card';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Send, Bot, User, Sparkles, Code, TrendingUp, BarChart3 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Message {
  id: string;
  content: string;
  sender: 'user' | 'ai';
  timestamp: Date;
  suggestions?: string[];
  codeGenerated?: boolean;
}

interface ChatInterfaceProps {
  onStrategyGenerated: (strategy: any) => void;
  onCodeGenerated: (code: any) => void;
}

const ChatInterface = ({ onStrategyGenerated, onCodeGenerated }: ChatInterfaceProps) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      content: "Hi! I'm your AI trading strategy assistant. Describe the strategy you'd like to create in plain English, and I'll help you build it step by step. What kind of trading strategy are you thinking about?",
      sender: 'ai',
      timestamp: new Date(),
      suggestions: [
        "Create a moving average crossover strategy",
        "Build an RSI mean reversion strategy", 
        "Design a breakout strategy with Bollinger Bands",
        "Make a scalping strategy for forex"
      ]
    }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const generateStrategy = (prompt: string) => {
    // Mock strategy generation based on prompt analysis
    const strategy = {
      id: Math.random().toString(36).substr(2, 9),
      name: `AI Generated Strategy`,
      description: prompt,
      type: prompt.toLowerCase().includes('scalp') ? 'Scalping' : 
            prompt.toLowerCase().includes('crossover') ? 'Trend Following' :
            prompt.toLowerCase().includes('rsi') ? 'Mean Reversion' : 'Custom',
      confidence: 85 + Math.floor(Math.random() * 10),
      indicators: extractIndicators(prompt),
      conditions: {
        entry: extractEntryConditions(prompt),
        exit: extractExitConditions(prompt)
      },
      riskManagement: {
        stopLoss: prompt.toLowerCase().includes('stop') ? '2%' : null,
        takeProfit: prompt.toLowerCase().includes('profit') ? '4%' : null
      }
    };

    onStrategyGenerated(strategy);
    return strategy;
  };

  const generateCode = (strategy: any) => {
    const code = {
      pineScript: `// ${strategy.name} - Generated by Trainflow AI
//@version=5
strategy("${strategy.name}", overlay=true)

// Indicators
${strategy.indicators.map((ind: any) => `${ind.name.toLowerCase().replace(/\s+/g, '_')} = ${ind.code}`).join('\n')}

// Entry Logic
${strategy.conditions.entry.map((cond: any) => `// ${cond}`).join('\n')}

// Exit Logic  
${strategy.conditions.exit.map((cond: any) => `// ${cond}`).join('\n')}

// Risk Management
${strategy.riskManagement.stopLoss ? `strategy.exit("Stop Loss", "Long", loss=${strategy.riskManagement.stopLoss})` : ''}
${strategy.riskManagement.takeProfit ? `strategy.exit("Take Profit", "Long", profit=${strategy.riskManagement.takeProfit})` : ''}`,

      mql4: `// ${strategy.name} - MQL4 Expert Advisor
#property copyright "Trainflow AI"
#property version   "1.00"

// Input Parameters
${strategy.riskManagement.stopLoss ? `input double StopLoss = ${parseFloat(strategy.riskManagement.stopLoss.replace('%', ''))};` : ''}
${strategy.riskManagement.takeProfit ? `input double TakeProfit = ${parseFloat(strategy.riskManagement.takeProfit.replace('%', ''))};` : ''}

void OnTick()
{
   // Strategy Implementation
   ${strategy.indicators.map((ind: any) => `// ${ind.name} logic here`).join('\n   ')}
}`
    };

    onCodeGenerated(code);
    return code;
  };

  const extractIndicators = (prompt: string) => {
    const indicators = [];
    if (prompt.toLowerCase().includes('rsi')) {
      indicators.push({ name: 'RSI', code: 'ta.rsi(close, 14)', period: 14 });
    }
    if (prompt.toLowerCase().includes('moving average') || prompt.toLowerCase().includes('ma')) {
      indicators.push({ name: 'Moving Average', code: 'ta.sma(close, 20)', period: 20 });
    }
    if (prompt.toLowerCase().includes('bollinger')) {
      indicators.push({ name: 'Bollinger Bands', code: 'ta.bb(close, 20, 2)', period: 20 });
    }
    if (prompt.toLowerCase().includes('macd')) {
      indicators.push({ name: 'MACD', code: 'ta.macd(close, 12, 26, 9)', period: 12 });
    }
    return indicators;
  };

  const extractEntryConditions = (prompt: string) => {
    const conditions = [];
    if (prompt.toLowerCase().includes('buy when')) {
      conditions.push('Buy signal detected based on your criteria');
    }
    if (prompt.toLowerCase().includes('sell when')) {
      conditions.push('Sell signal detected based on your criteria');
    }
    return conditions;
  };

  const extractExitConditions = (prompt: string) => {
    const conditions = [];
    if (prompt.toLowerCase().includes('stop loss')) {
      conditions.push('Stop loss triggered');
    }
    if (prompt.toLowerCase().includes('take profit')) {
      conditions.push('Take profit triggered');
    }
    return conditions;
  };

  const handleSend = async () => {
    if (!input.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      content: input,
      sender: 'user',
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    // Simulate AI processing
    setTimeout(() => {
      const strategy = generateStrategy(input);
      const code = generateCode(strategy);
      
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        content: `Great! I've analyzed your strategy and created a ${strategy.type} strategy with ${strategy.confidence}% confidence. I've generated the Pine Script and MQL4 code for you. You can see the live preview on the right and download the files when ready.

Here's what I found in your strategy:
• ${strategy.indicators.length} technical indicators
• Entry conditions: ${strategy.conditions.entry.length} rules
• Exit conditions: ${strategy.conditions.exit.length} rules
${strategy.riskManagement.stopLoss ? `• Stop Loss: ${strategy.riskManagement.stopLoss}` : ''}
${strategy.riskManagement.takeProfit ? `• Take Profit: ${strategy.riskManagement.takeProfit}` : ''}

Would you like me to modify anything or run a backtest?`,
        sender: 'ai',
        timestamp: new Date(),
        suggestions: [
          'Run a backtest on this strategy',
          'Modify the stop loss settings',
          'Add more indicators',
          'Change the timeframe'
        ],
        codeGenerated: true
      };

      setMessages(prev => [...prev, aiResponse]);
      setIsTyping(false);

      toast({
        title: 'Strategy Generated!',
        description: 'Your code is ready in the preview panel.',
      });
    }, 2000);
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInput(suggestion);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div className={`flex items-start space-x-3 max-w-[80%] ${message.sender === 'user' ? 'flex-row-reverse space-x-reverse' : ''}`}>
              <Avatar className="w-8 h-8 mt-1">
                {message.sender === 'ai' ? (
                  <>
                    <AvatarImage src="/ai-avatar.png" />
                    <AvatarFallback className="bg-primary text-primary-foreground">
                      <Bot className="w-4 h-4" />
                    </AvatarFallback>
                  </>
                ) : (
                  <>
                    <AvatarImage src="/user-avatar.png" />
                    <AvatarFallback className="bg-muted">
                      <User className="w-4 h-4" />
                    </AvatarFallback>
                  </>
                )}
              </Avatar>
              
              <div className={`${message.sender === 'user' ? 'text-right' : 'text-left'}`}>
                <Card className={`p-3 ${message.sender === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted/50'}`}>
                  <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                  {message.codeGenerated && (
                    <div className="flex items-center space-x-2 mt-2 pt-2 border-t border-border">
                      <Badge variant="secondary" className="text-xs">
                        <Code className="w-3 h-3 mr-1" />
                        Code Generated
                      </Badge>
                    </div>
                  )}
                </Card>
                
                {message.suggestions && (
                  <div className="mt-2 space-y-1">
                    {message.suggestions.map((suggestion, index) => (
                      <Button
                        key={index}
                        variant="ghost"
                        size="sm"
                        className="text-xs h-auto p-2 hover:bg-muted"
                        onClick={() => handleSuggestionClick(suggestion)}
                      >
                        {suggestion}
                      </Button>
                    ))}
                  </div>
                )}
                
                <p className="text-xs text-muted-foreground mt-1">
                  {message.timestamp.toLocaleTimeString()}
                </p>
              </div>
            </div>
          </div>
        ))}
        
        {isTyping && (
          <div className="flex justify-start">
            <div className="flex items-start space-x-3">
              <Avatar className="w-8 h-8 mt-1">
                <AvatarFallback className="bg-primary text-primary-foreground">
                  <Bot className="w-4 h-4" />
                </AvatarFallback>
              </Avatar>
              <Card className="p-3 bg-muted/50">
                <div className="flex items-center space-x-1">
                  <div className="w-2 h-2 bg-primary rounded-full animate-pulse"></div>
                  <div className="w-2 h-2 bg-primary rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></div>
                  <div className="w-2 h-2 bg-primary rounded-full animate-pulse" style={{ animationDelay: '0.4s' }}></div>
                </div>
              </Card>
            </div>
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="border-t border-border p-4">
        <div className="flex space-x-2">
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Describe your trading strategy..."
            className="flex-1 min-h-[60px] resize-none"
            rows={2}
          />
          <Button 
            onClick={handleSend} 
            disabled={!input.trim() || isTyping}
            size="icon"
            className="h-[60px] w-[60px]"
          >
            <Send className="w-4 h-4" />
          </Button>
        </div>
        
        <div className="flex flex-wrap gap-2 mt-2">
          <Button variant="outline" size="sm" onClick={() => handleSuggestionClick("Create a moving average crossover strategy")}>
            <TrendingUp className="w-3 h-3 mr-1" />
            MA Crossover
          </Button>
          <Button variant="outline" size="sm" onClick={() => handleSuggestionClick("Build an RSI mean reversion strategy")}>
            <BarChart3 className="w-3 h-3 mr-1" />
            RSI Strategy
          </Button>
          <Button variant="outline" size="sm" onClick={() => handleSuggestionClick("Design a breakout strategy")}>
            <Sparkles className="w-3 h-3 mr-1" />
            Breakout
          </Button>
        </div>
      </div>
    </div>
  );
};

export default ChatInterface;